
modLoader="javafml"

loaderVersion="[41,)"

license="All rights reserved"

[[mods]]

modId="reforgedarmory"
version="0.1 Alpha"
displayName="Reforged Armory"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="armormod.png"
#credits="Yes :]" #optional
authors="Purplik"

#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''
This mod aims to re-balance Minecraft's Armor system by adding new utility to it.
'''

[[dependencies.reforgedarmory]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reforgedarmory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
